// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"pixelmapYarnSpinner","status":true,"description":"PixelMap Yarn Spinner","parameters":{}},
{"name":"YEP_EventMiniLabel","status":true,"description":"v1.12 Creates miniature-sized labels over events to allow\nyou to insert whatever text you'd like in them.","parameters":{"Default Show":"true","Minimum Width":"136","Font Size":"20","X Buffer":"0","Y Buffer":"36","Battle Transition":"false"}}
];
